server:
  # 将使用此端口
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_all
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: admin888
    database: 1
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 500
    pool.min-idle: 0
    timeout: 0